### ISSUE TITLE
Dynamic left padding of image

### ISSUE THREAD

**Issue by danieltigse** [badoualy/morphy-toolbar#4]
If I don't setDisplayHomeAsUpEnabled as true there is a padding left unnecessary like this. Can you validate this?

![screenshot_20160921-174328](https://cloud.githubusercontent.com/assets/1870723/18731704/2fdaf646-8023-11e6-816f-3d4323c37a25.png)

**Comment by badoualy** [comment]
Did you try using `withContentMarginStart` to adjust the padding?
https://github.com/badoualy/morphy-toolbar/blob/master/library/src/main/java/com/github/badoualy/morphytoolbar/MorphyToolbarBuilder.java#L162

**Comment by danieltigse** [comment]
Yes, that is the solution.
