### ISSUE TITLE
How to rebuild the toolbar?

### ISSUE THREAD

**Issue by danieltigse** [badoualy/morphy-toolbar#5]
If I use the build function again, another toolbar is added above the actual. How can I remove actual morphyToolbar?

**Comment by badoualy** [comment]
Why would you want to build the toolbar again?

**Comment by danieltigse** [comment]
For example when you have fragments and you want to use morphy toolbar in one and not in other. You have to remove the morphy toolbar and rebuild it. But don't worry I fork the repo and make my own methods to hide or show elements.
